taskList = {
    "vmtoolsd.exe":"vmtool",
    "vmacthlp.exe":"vmtool",
    "VGAuthService.exe":"vmtool",
    "SynTPEnh.exe":"笔记本触摸板",
    "SynTPEnhService.exe":"笔记本触摸板",
    "vmware.exe":"VMware",
    "WGestures.exe":"鼠标手势软件",
    "spoolsv.exe":"打印机驱动程序",
    "RadeonSoftware.exe":"AMD驱动软件",
    "QQProtect.exe":"QQ安全防护进程（Q盾）",
    "powershell.exe":"Windows PowerShell",
    "OneDrive.exe":"Microsoft OneDrive",
    "NutstoreWatchDog.exe":"坚果云",
    "NutstoreDriverSvc.exe":"坚果云",
    "Everything.exe":"Everything 搜索",
    "DingTalk.exe":"钉钉",
    "clash-win64.exe":"clash",
    "chrome.exe":"chrome",
};
